routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::resource('pacients', 'PacientController', ['only' => [
    'store', 'update', 'destroy'
]]);
Route::resource('branches', 'BranchController', ['only' => [
    'store', 'update', 'destroy'
]]);

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    protected $fillable = ['name'];

    public function pacient() {
        return $this->hasOne('App\Pacient');
    }
}

app/Pacient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pacient extends Model
{
    protected $fillable = ['surname', 'name', 'patronymic', 'birth', 'address', 'diagnosis', 'note', 'branch_id'];

    public function branch() {
        return $this->belongsTo('App\Branch');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Branch::create($request->all());
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Branch $branch)
    {
        $branch->update($request->all());
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Pacient;
use Illuminate\Http\Request;
use App\Branch;

class HomeController extends Controller
{
    public function index() {
        $branches = Branch::all();
        $pacients = Pacient::all();

        return view('home', [
            'branches' => $branches,
            'pacients' => $pacients
        ]);
    }
}

app/Http/Controllers/PacientController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use App\Pacient;
use Illuminate\Http\Request;

class PacientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Pacient::create($request->all());
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pacient $pacient)
    {
        $pacient->update($request->all());
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pacient $pacient)
    {
        $pacient->delete();
        return redirect()->route('home');
    }
}

resources/views/home.blade.php
<!doctype html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{asset('bootstrap/css/bootstrap.min.css')}}">

    <link rel="stylesheet" href="{{asset('/css/main.css')}}">

    <title>EasyMED</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#pacientAdd">
        <span data-feather="plus"></span>
        Добавить
    </button>
    @include('modal.pacients.add')
    @include('modal.branches.add')

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Отделения
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    @if(isset($branches))
                        @foreach($branches as $branch)
                            <a class="dropdown-item" href="#">{{$branch->name}}</a>
                        @endforeach
                        <div class="dropdown-divider"></div>
                    @endif
                    <a class="dropdown-item" href="" data-toggle="modal" data-target="#branchAdd">
                        Добавить
                    </a>
                </div>
            </li>
            <li class="nav-item">

            </li>
        </ul>
        <input type="text" class="form-control" placeholder="Поиск" title="ФИО ДР Диагноз" id="search" autofocus oninput="search(this.value)">
    </div>
</nav>

@if(!count($pacients) == 0)
    <table class="table table-striped">
        <thead>
            <tr class="tab-header">
                <th scope="col">Фамилия</th>
                <th scope="col">Имя</th>
                <th scope="col">Отчество</th>
                <th scope="col">Дата рождения</th>
                <th scope="col">Адрес</th>
                <th scope="col">Диагноз</th>
                <th scope="col">Отделение</th>
                <th scope="col">Примечание</th>
                <th scope="col" class="text-center">Действие</th>
            </tr>
        </thead>
        <tbody id="defaultTable">
            @foreach($pacients as $pacient)
                @include('modal.pacients.edit')
                @include('modal.pacients.delete')
                <tr id="pac{{$pacient->id}}">
                    <td>{{$pacient->surname}}</td>
                    <td>{{$pacient->name}}</td>
                    <td>{{$pacient->patronymic}}</td>
                    <td>{{date('d.m.Y', strtotime($pacient->birth))}}</td>
                    <td>{{$pacient->address}}</td>
                    <td>{{$pacient->diagnosis}}</td>
                    <td>
                        @if(isset($pacient->branch))
                            {{$pacient->branch->name}}
                        @endif
                    </td>
                    <td>{{$pacient->note}}</td>
                    <td class="text-center">
                        <a class="nav-link active action-link" href="" title="Редактировать" data-toggle="modal" data-target="#pacientEdit{{$pacient->id}}">
                            <span data-feather="edit"></span>
                        </a>
                        <a class="nav-link active action-link" href="" title="Удалить" data-toggle="modal" data-target="#pacientDel{{$pacient->id}}">
                            <span data-feather="delete"></span>
                        </a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@else
    <div class="container h-100">
        <h1 class="text-center p-5">Нет пациентов</h1>
    </div>
@endif

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{{asset('js/jquery-3.3.1.slim.min.js')}}"></script>
<script src="{{asset('js/popper.min.js')}}"></script>
<script src="{{asset('bootstrap/js/bootstrap.min.js')}}"></script>

<!-- Icons -->
<script src="{{asset('js/feather.min.js')}}"></script>
<script>
    feather.replace()
</script>

<script>
    function search(text) {

        var defTab;
        defTab = $("#defaultTable");

        if (text.length > 2) {
            clearSearch();
            var keywords = text.split(' ');

            defTab.addClass('hidetr');

            var pacients = {!! json_encode($pacients) !!}

            pacients.forEach(function(item, i, arr) {
                var copy_item = Object.assign({}, item);
                var search_array = [];
                var success;

                for (var k in copy_item) {
                    if (k == 'created_at' || k == 'updated_at'  || k == 'id' || k == 'branch_id' || k == 'branch' || k == 'address' || k == 'note' || copy_item[k] == null) {
                        delete copy_item[k];
                    }
                }

                keywords.forEach(function (keyword) {
                    var re = new RegExp(keyword, 'i');
                    var result;

                    for(var key in copy_item) {

                        if (keywords.length > 1) {
                            var full_match = new RegExp('^'+keyword+'$', 'i');

                            if (keyword !== keywords[keywords.length - 1]) {
                                result = copy_item[key].search(full_match);
                                if (result == 0) {
                                    search_array[search_array.length] = result;
                                    delete copy_item[key];
                                }
                            }
                            else {
                                if (keywords.length-1 == search_array.length) {
                                    result = copy_item[key].match(re);
                                    if (result) {
                                        success = 1;
                                    }
                                }
                            }
                        }
                        else {
                            result = copy_item[key].match(re);
                            if (result) {
                                success = 1;
                            }
                        }
                    }
                });

                if (success == 1) {
                    var my_not_null = function (param) {
                        if (param !== null) {
                            return param.name;
                        }
                    };

                    $('#pac'+item.id+'').addClass('showtr');
                }
            });
        }
        else {
            resetTable()
        }
    }
    function clearSearch() {
        $(".showtr").removeClass('showtr');
    }
    function resetTable() {
        clearSearch();

        var defTab;
        defTab = $("#defaultTable");

        defTab.removeClass('hidetr');
    }
</script>
</body>
</html>

resources/views/modal/branches/add.blade.php
<div class="modal fade" id="branchAdd" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Добавление отделения</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('branches.store')}}" method="post">
                {{ csrf_field() }}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputNameBranch">Название</label>
                        <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="inputNameBranch" name="name" placeholder="Название" value="{{$branch->name or ""}}" required autofocus>
                        @if ($errors->has('name'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modal/pacients/add.blade.php
<div class="modal fade" id="pacientAdd" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавление пациента</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('pacients.store')}}" method="post">
                {{ csrf_field() }}
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputSurname">Фамилия</label>
                            <input type="text" class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" id="inputSurname" name="surname" placeholder="Фамилия" value="{{$pacient->surname or ""}}" required>
                            @if ($errors->has('surname'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('surname') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputName">Имя</label>
                            <input type="text" class="form-control" id="inputName" placeholder="Имя" name="name">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputPatronymic">Отчество</label>
                            <input type="text" class="form-control" id="inputPatronymic" placeholder="Отчество" name="patronymic">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputDate">Дата рождения</label>
                            <input type="date" class="form-control" id="inputDate" max="{{date('d/m/Y')}}" name="birth">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputAddress">Адрес</label>
                        <input type="text" class="form-control" id="inputAddress" placeholder="Город, улица, дом, квартира" name="address">
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputDiagnosis">Диагноз</label>
                            <input type="text" class="form-control" id="inputDiagnosis" placeholder="Диагноз" name="diagnosis">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputBranch">Отделение</label>
                            <select id="inputBranch" class="form-control" @if(!isset($branches)) disabled @endif name="branch_id">
                                <option></option>
                                @foreach($branches as $branch)
                                    <option value="{{$branch->id}}">{{$branch->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputNote">Примечание</label>
                        <input type="text" class="form-control" id="inputNote" placeholder="Дополнительная информация" name="note">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modal/pacients/delete.blade.php
<div class="modal fade" id="pacientDel{{$pacient->id}}" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Удаление пациента</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('pacients.destroy', $pacient)}}" method="post">
                <input type="hidden" name="_method" value="DELETE">
                {{ csrf_field() }}
                <div class="modal-body">
                    <h5>Удалить пациента {{$pacient->surname}} {{$pacient->name}} {{$pacient->patronymic}}?</h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modal/pacients/edit.blade.php
<div class="modal fade" id="pacientEdit{{$pacient->id}}" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Редактирование пациента</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('pacients.update', $pacient)}}" method="post">
                <input type="hidden" name="_method" value="PUT">
                {{ csrf_field() }}
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputSurname">Фамилия</label>
                            <input type="text" class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" id="inputSurname" name="surname" placeholder="Фамилия" value="{{$pacient->surname or ""}}" required>
                            @if ($errors->has('surname'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('surname') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputName">Имя</label>
                            <input type="text" class="form-control" id="inputName" placeholder="Имя" name="name" value="{{$pacient->name or ""}}">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputPatronymic">Отчество</label>
                            <input type="text" class="form-control" id="inputPatronymic" placeholder="Отчество" name="patronymic" value="{{$pacient->patronymic or ""}}">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputDate">Дата рождения</label>
                            <input type="date" class="form-control" id="inputDate" max="{{date('d/m/Y')}}" name="birth" value="{{$pacient->birth or ""}}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputAddress">Адрес</label>
                        <input type="text" class="form-control" id="inputAddress" placeholder="Город, улица, дом, квартира" name="address" value="{{$pacient->address or ""}}">
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputDiagnosis">Диагноз</label>
                            <input type="text" class="form-control" id="inputDiagnosis" placeholder="Диагноз" name="diagnosis" value="{{$pacient->diagnosis or ""}}">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputBranch">Отделение</label>
                            <select id="inputBranch" class="form-control" @if(!isset($branches)) disabled @endif name="branch_id">
                                <option></option>
                                @foreach($branches as $branch)
                                    <option value="{{$branch->id}}" @if($pacient->branch_id == $branch->id) selected @endif>{{$branch->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputNote">Примечание</label>
                        <input type="text" class="form-control" id="inputNote" placeholder="Дополнительная информация" name="note" value="{{$pacient->note or ""}}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>